### ISSUE TITLE
Does not support parameters

### ISSUE THREAD

**Issue by ivan-prodanov** [PowerShell/PackageManagementProviderResource#12]
Let's say I register chocolatey and want to install VS 2015 with Web Dev Tools feature (which is disabled by default). I normally could by adding the "/feature ..." to the command line, but this great DSC resource doesn't pass any arguments to Install-Package. Please check AdditionalArguments.

**Comment by Krishna-Vutukuri** [comment]
@ivan-prodanov I fixed this issue with generic PackageManagement resource. Is it possible for you to look at the definition at https://github.com/PowerShell/PackageManagementProviderResource/blob/master/DSCResources/MSFT_PackageManagement/MSFT_PackageManagement.schema.mof
