### ISSUE TITLE
Adding a "scope" property to PackageManagementSource

### ISSUE THREAD

**Issue by mprahl** [PowerShell/PackageManagementProviderResource#3]
Hello,
I'm currently using the DSC Resource "PackageManagementSource" and realized that the changes are only applying to the "System" user account. I'd like the ability to have this apply system-wide.

Thank you for your time.

**Comment by Krishna-Vutukuri** [comment]
@PrahlM93 I added a new generic PackageManagement DSC resource. This has AdditionalParameters which can be used for your needs. Can you please give this a try?

**Comment by Krishna-Vutukuri** [comment]
Thanks!
