### ISSUE TITLE
Add parameter on Install-Module to AllowClobber

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/PackageManagementProviderResource#38]
Currently the use of the resource PSModule does not have any parameter to allowClobber.

If there are Cmdlets on the machine that already exist, then the module install with fail.

**Comment by travis-sobeck** [comment]
Yes!!! or be even more general and allow ANY switch parameter to be passed in

**Comment by brwilkinson** [comment]
closing since this repo is no longer in use.
