### ISSUE TITLE
DSC Resource that is a wrapper of Register-PSRepository

### ISSUE THREAD

**Issue by mprahl** [PowerShell/PackageManagementProviderResource#4]
Hello,
I'd like to be able to set PowerShell repositories for a specific user, the LCM, or system-wide so that we can use the PSModule resource on an internal Nuget repository, not just the PowerShell Gallery.

Thank you for your time.

**Comment by vercellone** [comment]
+1

**Comment by jianyunt** [comment]
@PrahlM93, @vercellone  To set a private repo, please see https://github.com/PowerShell/PSPrivateGallery.

**Comment by mprahl** [comment]
@jianyunt I don't think that is what we are looking for. We are really looking for a wrapper for Register-PSRepository.

Although, now we can run DSC resources as other users, so this issue is longer needed.
